name = "url-shortener"
main = ".open-next/worker.js"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat"]

# Assets configuration for serving static files
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "URL_SHORTENER_KV"
id = "bdb4249002e243c1b41f2bf107982aa7"
